### ISSUE TITLE
JoWilder: NumGuesses feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#16]
Number of guesses a player made before giving the correct response.

The features/sub-features are:
(base) - the number of guesses a player made before giving the correct response. (previously called `num_guesses`)

It should be configured in JOWILDER.json as a per_count feature, with prefix = `qz` and count = `19`.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: NumGuesses feature](https://trello.com/c/OaAJVCca/848-jowilder-numguesses-feature)

**Comment by LswaN58** [comment]
This feature is called "num_guesses" in the old JoWilderExtractor.
It should be configured in JOWILDER.json as a per_count feature, with prefix = Q and count = 19, just as before.

**Comment by hahashuo** [comment]
441c532e16bbbf725c26bf12290f36a121f086b5
