### ISSUE TITLE
JoWilder: QuestionAnswers feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#17]
A list of all answers a player attempted on a question

The features/sub-features are:
(base) - list of all answers a player attempted on a question. (previously called `answers`)

It should be configured in JOWILDER.json as a per_count feature, with prefix = `qz` and count = `19`.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: QuestionAnswers feature](https://trello.com/c/Onu9J9TA/847-jowilder-questionanswers-feature)

**Comment by LswaN58** [comment]
This feature is called "answers" in the old JoWilderExtractor.
It should be configured in JOWILDER.json as a per_count feature, with prefix = Q and count = 19, just as before.

**Comment by hahashuo** [comment]
441c532e16bbbf725c26bf12290f36a121f086b5
