### ISSUE TITLE
JoWilder: SurveyItem feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#18]
A single feature class, with a couple of subfeatures:

The features/sub-features are:
(base) - the raw 'index' or int value of the response (basically, `n` where the response was the `n`th option). (previously called `sa_index`)
Text - The text corresponding to the response (previously called `sa_text`)
Time - the time taken to answer the survey question (previously called `sa_time`)
ResponseChanges - the number of times the person changed their response before submitting the survey item. (previously called `sa_num_answers`)

It should be configured in JOWILDER.json as a per_count feature, with prefix = `sa` and count = `18`.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SurveyResponse feature](https://trello.com/c/UXZDsNQd/846-jowilder-surveyresponse-feature)

**Comment by LswaN58** [comment]
This feature should be configured in JOWILDER.json as a per_count feature, with prefix = SA, and count 18, just as before.

**Comment by hahashuo** [comment]
488626896e3b427b81d18a4ffa0bac4abbb05366

**Comment by hahashuo** [comment]
488626896e3b427b81d18a4ffa0bac4abbb05366
