### ISSUE TITLE
JoWilder: InteractionTime feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#20]
A feature for the time spent in an interaction.
It will include a subfeature for the time spent the first time the interaction was encountered.

The sub-features are:
(base) - the total time spent in this interaction, across all times having the interaction (previously called `itotal_duration`)
FirstEncounter - the time spent on the first time having this interaction (previously called `ifirst_enc_duration`)
To - the time taken to reach the interaction, maybe? This should do whatever the previous `itime_to` feature did (previously called `itime_to`).

This should be configured as a per_count feature, with prefix = `int` and count = `189`, as before.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: InteractionDuration feature](https://trello.com/c/F00FzIJy/853-jowilder-interactionduration-feature)

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: InteractionTime feature](https://trello.com/c/F00FzIJy/853-jowilder-interactiontime-feature)

**Comment by hahashuo** [comment]
0724ad8213cee27a546315fba47b3c24c7b4a9d6

**Comment by hahashuo** [comment]
affe310038933df9270c683dea266ef8c3579e38
