### ISSUE TITLE
JoWilder: InteractionCount

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#21]
A feature for set statistics on an interaction.
It will include a subfeature for the time spent the first time the interaction was encountered.

The sub-features are:
(base) - The number of times the player had this interaction (previously called `inum_enc`)
Boxes - the number of boxes read in the interaction (previously called `ifirst_enc_boxes_read`)
Words - the number of words read in the interaction (previously called `ifirst_enc_words_read`)

This should be configured as a per_count feature, with prefix = `int` and count = `189`, as before.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: InteractionMetadata feature](https://trello.com/c/FGimgSoD/852-jowilder-interactionmetadata-feature)

**Comment by hahashuo** [comment]
0724ad8213cee27a546315fba47b3c24c7b4a9d6

**Comment by hahashuo** [comment]
70d1c077f713388a6ca0665b21b0786ad661cedf
