### ISSUE TITLE
JoWilder: InteractionName

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#22]
A feature for the name of an interaction.

The sub-features are:
(base) - the fqid of the interaction (not a previous feature)

This should be configured as a per_count feature, with prefix = int and count = 189.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: InteractionName feature](https://trello.com/c/Dz1NNAcs/854-jowilder-interactionname-feature)

**Comment by hahashuo** [comment]
70d1c077f713388a6ca0665b21b0786ad661cedf
