### ISSUE TITLE
JoWilder: Clicks

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#25]
A feature to calculate the total number of clicks in a session.

The sub-features are:
(base) - The number of clicks in a session (previously called `sess_count_clicks`).
AverageTimeBetween - the overall average time between click events (previously called `sess_avg_time_between_clicks`).

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionClicks feature](https://trello.com/c/YafvndeN/857-jowilder-sessionclicks-feature)

**Comment by hahashuo** [comment]
245d0b9233ae85f6fe68803919610b76adbe0096

**Comment by hahashuo** [comment]
7b2b2a068b59a7bbfac8d75e28dfb5960f14fd62
