### ISSUE TITLE
JoWilder: Hovers

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#26]
A feature to calculate the total number of hovers in a session.

The sub-features are:
(base) - The number of hovers in a session (previously called sess_count_hovers).

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionHovers feature](https://trello.com/c/bvljrFrh/858-jowilder-sessionhovers-feature)

**Comment by hahashuo** [comment]
bd3c383a5bd6bafb469a26de53aec3e4dde8f5cb
