### ISSUE TITLE
JoWilder: MeaningfulActions

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#27]
A feature to calculate the total number of 'meaningful' clicks in a session. That is, the number of navigation clicks on items/objects/people/portholes + number of clicks on map locations

The sub-features are:
(base) - The number of 'meaningful' clicks in a session (previously called `sess_meaningful_action_count`).

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionMeaningfulActions feature](https://trello.com/c/tUwPGXkx/859-jowilder-sessionmeaningfulactions-feature)

**Comment by hahashuo** [comment]
738cf7d17c94f640f9303e9248d2ed0f663c359e

**Comment by hahashuo** [comment]
af032026b34affa966d98d29551c729c8225119f
