### ISSUE TITLE
JoWilder: EventCount

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#28]
A feature to calculate the total number of events in a session.

The sub-features are:
(base) - The number of events in a session (previously called sess_EventCount).

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionEventCount feature](https://trello.com/c/v9bxiOon/860-jowilder-sessioneventcount-feature)

**Comment by hahashuo** [comment]
93b546032db7263d2d9baf2f659eb01fbc180964
