### ISSUE TITLE
JoWilder: NotebookUses

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#29]
A feature to calculate the total number of times a player used the notebook in a session, i.e. the number of times the player opened the notebook over the whole game.

The sub-features are:
(base) - The number of notebook uses in a session (previously called `sess_count_notebook_uses`).

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionNotebookUses feature](https://trello.com/c/rSEJ0Xb8/861-jowilder-sessionnotebookuses-feature)

**Comment by hahashuo** [comment]
1bb8378b19fabdb57a7c995e49b708ae53bd2b79
