### ISSUE TITLE
JoWilder: SessionDuration

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#30]
A feature to calculate the total time spent in a session.

The sub-features are:
(base) - The total time in a session (previously called `sessDuration`).

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionDuration feature](https://trello.com/c/AJyq2aDC/867-jowilder-sessionduration-feature)

**Comment by hahashuo** [comment]
c55ee73f0cfea1357cef575eb4bf5e3f58a43dd3
