### ISSUE TITLE
JoWilder: IdleState

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#31]
A feature to calculate the total number of clicks in a session. This feature should override `BaseFeatureSuffix()` to return `"Time"`, so that the base feature name becomes `IdleTime`.

The sub-features are:
(base) - time spent idle in session (past IDLE_THRESH seconds without clicks/hovers) (previously called `sess_time_idle`).
Count- the number of times the player entered an idle state (previously called `sess_count_idle`).

This should be configured as an aggregate feature.

**Comment by hahashuo** [comment]
Try adding args in the json file

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: IdleState feature](https://trello.com/c/Eo3HWryM/868-jowilder-idlestate-feature)

**Comment by hahashuo** [comment]
26ce48124998beeabe13ae3e5963381747e312b4

**Comment by hahashuo** [comment]
531a2c288d56f50118df4570b4f4f966b5300688
