### ISSUE TITLE
JoWilder: ActiveStateTime

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#32]
A feature to calculate the time spent actively playing the game.

The sub-features are:
(base) - The total time a player spent in the 'active' state; that is, no more than THRESHOLD time passed since last event (previously called `sess_time_active`
`Clicking` - Similar to the base feature, but ignores hovers when calculating whether player was active or not (previously called `sess_time_active_clicking`.

General algorithm for calculating the base feature:
Check each hover and click event.
If difference between the new event's timestamp and the previous timestamp is <= THRESHOLD, add that difference to the total active time.

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: ActiveStateTime](https://trello.com/c/DaKZhIQi/869-jowilder-activestatetime)

**Comment by hahashuo** [comment]
5a3b5a058c64862e394f511fa60a3cfcfb3d01c7

**Comment by hahashuo** [comment]
531a2c288d56f50118df4570b4f4f966b5300688
