### ISSUE TITLE
JoWilder: FirstInteraction

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#33]
A feature to show which interaction a player had first within the game session.

The sub-features are:
(base) - The first interaction a player encountered in the game (replaces `start_level`)

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: FirstInteraction](https://trello.com/c/xE4fSkkL/870-jowilder-firstinteraction)

**Comment by hahashuo** [comment]
b20b6505c1fef5084a65ef8fa6c18fda2c0b4f80
