### ISSUE TITLE
JoWilder: LastInteraction

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#34]
A feature to show which interaction a player last had within the game session.

The sub-features are:
(base) - The last interaction a player encountered in the game (replaces max_level)

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: LastInteraction](https://trello.com/c/y4elxnTe/871-jowilder-lastinteraction)

**Comment by hahashuo** [comment]
a4dc17f87809640898c4c4c6d55d3633b81c591d

**Comment by hahashuo** [comment]
627dadf027704cfb74e37baa9d5c90be5f206d0c
