### ISSUE TITLE
JoWilder: SessionStart

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#35]
A feature to record the date and time on which the gameplay session started. Override the `BaseFeatureSuffix()` function to make `Date` the suffix of the base feature.

The sub-features are:
(base) - The date on which the session started (originally split into `play_year`, `play_month`, `play_day`).
Time - The time of day (UTC) at which the session started (originally split into `play_hour`, `play_minute`, and `play_second`).
Year - The year in which the session started (originally `play_year`).
Month - The month in which the session started (originally `play_month`)
Hour - The hour at which the session started (originally `play_hour`)

This should be configured as an aggregate feature.

**Comment by LswaN58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: SessionStart feature](https://trello.com/c/vhyCEccD/872-jowilder-sessionstart-feature)

**Comment by hahashuo** [comment]
f459b64c1f8f9616ce452a0dd9e67dc6c19989e3
