### ISSUE TITLE
JoWilder: UsedContinue

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#36]
A feature to indicate whether the session began from the "continue" button; i.e. whether this session continued from the ending savecode of another session.

The sub-features are:
(base) - 1 if continuing a game, 0 if not (previously called `continue`).

This should be configured as an aggregate feature.

**Comment by hahashuo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: UsedContinue feature](https://trello.com/c/XdrVmQBJ/882-jowilder-usedcontinue-feature)

**Comment by hahashuo** [comment]
8dff3ae0e94aa77955b6cc46395e7809a6c7f4f7
