### ISSUE TITLE
JoWilder: UsedSaveCode

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#37]
A feature to show which save code, if any, a player used as a starting point for their game.

The sub-features are:
(base) - The save code the player used, if any, otherwise 0 (previously `save_code`)

This should be configured as an aggregate feature.

**Comment by hahashuo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWIlder: UsedSaveCode](https://trello.com/c/PcdUugEm/883-jowilder-usedsavecode)

**Comment by hahashuo** [comment]
18bcec1b82c6a9296b788ebad54305b54de5da39

**Comment by hahashuo** [comment]
8e118b380888b797358f58fa0f642306d41d71a3
