### ISSUE TITLE
JoWilder: UserEnabled

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#38]
A feature to show which options a user enabled. Override `BaseFeatureSuffix` to append `Fullscreen` to the base feature name.

The sub-features are:
(base) - 1 if the player had fullscreen enabled, otherwise 0 (previously `fullscreen`).
Music - 1 if the player had music enabled, otherwise 0 (previously `music`).
HQGraphics- 1 if the player had hq graphics enabled, otherwise 0 (previously `hq`).

This should be configured as an aggregate feature.

**Comment by hahashuo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: UserEnabled](https://trello.com/c/0yKXUivW/885-jowilder-userenabled)

**Comment by hahashuo** [comment]
cd6085ff8641da126c5da1365ef611bac22c8583

**Comment by hahashuo** [comment]
e007e293df5bb5011bdb4c7667745229cad0140e
