### ISSUE TITLE
JoWilder: GameScript

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#39]
A feature to show which version of the script the player saw. Override `BaseFeatureSuffix` to append `Name` to the base feature name.

The sub-features are:
(base) - The name of the script the player saw (currently, the values are "Dry", "No Snark", "No Humor", and "Normal") (previously `script_type`).
Version- The version of whichever script the player saw (previously `script_version`).

This should be configured as an aggregate feature.

**Comment by hahashuo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: GameScript](https://trello.com/c/M4LcKXXf/884-jowilder-gamescript)

**Comment by hahashuo** [comment]
993d3fbacaff74b20aae5d93dc860085bb452ae4

**Comment by hahashuo** [comment]
e5f45eca28f8a846b1e84fed8c6948b9bb9d025e
