### ISSUE TITLE
JoWilder: GameVersion

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#40]
A feature to show which version of the game the player played.

The sub-features are:
(base) - The game version found in the player's event data.

This should be configured as an aggregate feature.

**Comment by hahashuo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JoWilder: GameVersion](https://trello.com/c/64JoKPTD/886-jowilder-gameversion)

**Comment by hahashuo** [comment]
cd6085ff8641da126c5da1365ef611bac22c8583

**Comment by hahashuo** [comment]
e007e293df5bb5011bdb4c7667745229cad0140e
