### ISSUE TITLE
Journalism: TopAttribute feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#87]
Feature whose value is an int, indicating the value of the highest attribute the player has.
Includes one subfeature:
1. `Names` : A list of the names of all attributes that had the top value (e.g. a player could have both Tech and Trust at 5, and all others <= 4).

Only runs at the session and player level.

**Comment by zstud04** [comment]
253a746c979aa6db22929a1ed7ba3a38d8fb6342
