### ISSUE TITLE
Journalism: WorstAttribute feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#90]
Feature whose value is an int, indicating the value of the lowest attribute the player has.
Includes one subfeature:
1. `Names` : A list of the names of all attributes that had the lowest value (e.g. a player could have both Tech and Trust at 2, and all others >= 3).

Only runs at the session and player level.

**Comment by zstud04** [comment]
71233f9b777c747c86d47bc667bd7979281841ef
