### ISSUE TITLE
Journalism: WorstPlayerAttribute feature

### ISSUE THREAD

**Issue by LswaN58** [opengamedata/opengamedata-core#91]
A per-count feature, with prefix `attr`.
This is per-attribute, so a range of 0-5.
It only runs at population level.

It should be a second-order feature, that takes `WorstAttribute-Names` as input.
The value of the base feature should be the name of the attribute (you can hard-code the mapping; someday we'll allow you to just define a list and have that directly in the feature name prefix...).
There should be one subfeature:
1. `Count` : An int counting the number of times the given attribute appeared in the list of a player's worst attributes. It should only count when the given `FeatureData` event has a mode of `ExtractionMode.PLAYER`. Suppose the hard-coded list was `attributes = ["Tech", "Trust", ...]`, then the feature can just check if the `FeatureData` value (a list) contains `attributes[self.CountIndex]`. It can then count the number of times this is true.

From all this, we should end up with a table that looks something like:
| attr0_WorstPlayerAttribute | attr0_WorstPlayerAttribute-Count | attr1_WorstPlayerAttribute | attr1_WorstPlayerAttribute-Count | ... |
| ---                                  | ---                                             | ---                                  | ---                                             | --- |
| 'Tech'                              | 11                                              | 'Trust'                             | 17                                              | ... |

**Comment by zstud04** [comment]
eb8f693719efa270abceac312db27a27cceb09a0
